// Local enum definitions — mirrors prisma/schema.prisma
// These are used for DTOs and guards until `prisma generate` is run in your environment.

export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  STAFF = 'STAFF',
  PUBLIC = 'PUBLIC',
}

export enum NewsStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum NewsTag {
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  EVENT = 'EVENT',
  NOTICE = 'NOTICE',
  PROJECT = 'PROJECT',
  TENDER = 'TENDER',
}

export enum ServiceCategory {
  CIVIL_REGISTRATION = 'CIVIL_REGISTRATION',
  LAND_ADMINISTRATION = 'LAND_ADMINISTRATION',
  BUSINESS_LICENSE = 'BUSINESS_LICENSE',
  AGRICULTURE = 'AGRICULTURE',
  HEALTH = 'HEALTH',
  EDUCATION = 'EDUCATION',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  SOCIAL_SERVICES = 'SOCIAL_SERVICES',
  FINANCE = 'FINANCE',
  OTHER = 'OTHER',
}

export enum DocumentType {
  BUDGET_REPORT = 'BUDGET_REPORT',
  PROCUREMENT_PLAN = 'PROCUREMENT_PLAN',
  PERFORMANCE_REPORT = 'PERFORMANCE_REPORT',
  POLICY = 'POLICY',
  GUIDELINE = 'GUIDELINE',
  TENDER_DOCUMENT = 'TENDER_DOCUMENT',
  ANNUAL_PLAN = 'ANNUAL_PLAN',
  OTHER = 'OTHER',
}

export enum ApplicationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  REQUIRES_DOCUMENTS = 'REQUIRES_DOCUMENTS',
}
